# Generated by Django 6.0.7 on 2026-08-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_blood_group_employee_city_employee_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='manager_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
