# Generated by Django 6.0.7 on 2026-07-23 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('employees', '0002_employee_blood_group_employee_city_employee_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(choices=[('Laptop', 'Laptop'), ('Monitor', 'Monitor'), ('Keyboard & Mouse', 'Keyboard & Mouse'), ('Headset', 'Headset'), ('ID Card', 'ID Card'), ('Access Card', 'Access Card')], max_length=100)),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Available', 'Available'), ('Returned', 'Returned'), ('Damaged', 'Damaged')], default='Assigned', max_length=20)),
                ('assigned_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='employees.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
