# Generated by Django 6.0.7 on 2026-07-27 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual Leave', 'Casual Leave'), ('Sick Leave', 'Sick Leave'), ('Personal Leave', 'Personal Leave'), ('Annual Leave', 'Annual Leave'), ('Festival Leave', 'Festival Leave')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Review', 'In Review')], default='Pending', max_length=20)),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
