# Generated by Django 6.0.7 on 2026-07-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('Meeting', 'Meeting'), ('Holiday', 'Holiday'), ('Reminder', 'Reminder')], max_length=20),
        ),
    ]
