# Generated by Django 6.0.7 on 2026-07-28 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=150)),
                ('location', models.CharField(default='Unknown', max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('device', models.CharField(max_length=150)),
                ('location', models.CharField(default='Unknown', max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_fa_enabled', models.BooleanField(default=False)),
                ('two_fa_method', models.CharField(choices=[('auth-app', 'Authenticator App'), ('sms', 'SMS'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='auth-app', max_length=30)),
                ('biometric_enabled', models.BooleanField(default=False)),
                ('biometric_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('faceid', 'Face ID')], default='fingerprint', max_length=20)),
                ('recovery_email', models.EmailField(blank=True, max_length=254)),
                ('recovery_phone', models.CharField(blank=True, max_length=20)),
                ('security_question', models.TextField(blank=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=20)),
                ('font_size', models.IntegerField(default=16)),
                ('high_contrast', models.BooleanField(default=False)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_push', models.BooleanField(default=True)),
                ('notify_attendance', models.BooleanField(default=True)),
                ('notify_announcements', models.BooleanField(default=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('en-us', 'English (US)'), ('en-gb', 'English (UK)'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('hi', 'Hindi'), ('kn', 'Kannada')], default='en', max_length=20)),
                ('date_format', models.CharField(default='dd-mm-yyyy', max_length=30)),
                ('time_format', models.CharField(default='12', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('dashboard_layout', models.CharField(choices=[('compact', 'Compact'), ('comfortable', 'Comfortable'), ('detailed', 'Detailed')], default='compact', max_length=30)),
                ('dashboard_widgets', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
