# Generated by Django 6.0.7 on 2026-08-05 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamchat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'id']},
        ),

        migrations.AddField(
            model_name='groupmember',
            name='joined_at',
            field=models.DateTimeField(
                auto_now_add=True,
                null=True
            ),
        ),

        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(
                upload_to='chat_attachments/'
            ),
        ),

        migrations.AlterField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='group_memberships',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.AlterField(
            model_name='readreceipt',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='read_messages',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]