# Generated by Django 6.0.7 on 2026-08-06 04:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamchat', '0002_alter_chatmessage_options_groupmember_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
