# Generated by Django 6.0.7 on 2026-08-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamchat', '0004_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
