# Generated by Django 6.0.7 on 2026-08-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamchat', '0005_attachment_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
