# Generated by Django 6.0.7

import teamchat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "teamchat",
            "0008_meeting_participant_alter_meeting_group"
        ),
    ]

    operations = [

        migrations.AlterModelOptions(
            name="meeting",
            options={},
        ),

        migrations.AddField(
            model_name="meeting",
            name="meeting_id",
            field=models.CharField(
                default=teamchat.models.generate_meeting_id,
                editable=False,
                max_length=20,
                unique=True,
            ),
        ),

        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=models.TextField(
                blank=True,
                null=True,
            ),
        ),

        migrations.AlterField(
            model_name="meeting",
            name="venue",
            field=models.CharField(
                default="Virtual Meeting",
                max_length=255,
            ),
        ),
    ]