# Generated by Django 6.0.7 on 2026-08-09 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_blood_group_employee_city_employee_country_and_more'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('employee', 'Employee Report'), ('manager', 'Manager Report')], max_length=20)),
                ('department', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('DevOps', 'DevOps'), ('Front End', 'Front End'), ('Data Analyst', 'Data Analyst')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('report_text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('sent', 'Sent')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type'], name='reports_rep_report__dbb097_idx'), models.Index(fields=['department'], name='reports_rep_departm_b7b274_idx'), models.Index(fields=['employee'], name='reports_rep_employe_6feb07_idx'), models.Index(fields=['status'], name='reports_rep_status_c732ef_idx')],
            },
        ),
    ]
