# Generated by Django 6.0.7 on 2026-08-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TaskReport',
        ),
    ]
