# Generated by Django 6.0.7 on 2026-08-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_department_delete_taskreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_report__dbb097_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_departm_b7b274_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_employe_6feb07_idx',
        ),
        migrations.RemoveIndex(
            model_name='report',
            name='reports_rep_status_c732ef_idx',
        ),
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('employee', 'Employee Report'), ('manager', 'Manager / Team Lead Report')], default='employee', max_length=20),
        ),
    ]
