# Generated by Django 6.0.7 on 2026-07-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_attachments/'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='employee_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
    ]
