# Generated by Django 6.0.7 on 2026-08-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_options_alter_tasks_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='approval_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='tasks',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
