# Generated by Django 6.0.7 on 2026-08-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasks_approval_status_tasks_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['due_date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
