# Generated by Django 6.0.7 on 2026-08-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval_stage',
            field=models.CharField(choices=[('TEAM_LEAD', 'Team Lead Approval'), ('MANAGER', 'Manager Approval'), ('COMPLETED', 'Completed')], default='TEAM_LEAD', max_length=20),
        ),
    ]
