# Generated by Django 6.0.7 on 2026-08-06 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_schedule_options_schedule_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='schedules.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_participant_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'schedules_scheduleparticipant',
                'unique_together': {('schedule', 'user')},
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='employee_schedules', through='schedules.ScheduleParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
