# Generated by Django 6.0.7 on 2026-07-22 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Announcement', 'Announcement'), ('Task', 'Task'), ('Meeting', 'Meeting'), ('Alert', 'Alert'), ('Leave', 'Leave'), ('Birthday', 'Birthday')], default='Announcement', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employees.employee'),
        ),
    ]
