# Generated by Django 6.0.7 on 2026-08-07 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_group_notification_meeting'),
        ('schedules', '0004_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='meeting',
        ),
        migrations.AddField(
            model_name='notification',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedule'),
        ),
    ]
